version: '3.8'

services:
  uci-cycling:
    image: ghcr.io/TON_GITHUB_USER/uci-cycling:latest
    container_name: uci-cycling
    restart: unless-stopped
    ports:
      - "8282:80"
    environment:
      - NODE_ENV=production
